# Generated by Django 4.2.7 on 2023-11-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_id',
            field=models.IntegerField(default=1, max_length=100),
        ),
    ]
