# Generated by Django 4.2.7 on 2023-11-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_remove_quiz_name_quiz_created_at_quiz_quiz_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
