# Generated by Django 4.2.7 on 2023-11-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0008_alter_quiz_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_id',
            field=models.IntegerField(default=1, max_length=100, unique=True),
        ),
    ]
