# Generated by Django 4.2.7 on 2023-11-29 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0009_alter_quiz_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_registered', models.ManyToManyField(blank=True, to='quiz_app.topic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
