# Generated by Django 4.2.7 on 2023-11-30 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0010_quiz_assigned_users_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='topic',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
