# Generated by Django 4.2.7 on 2023-11-30 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0012_student_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='assigned_users',
            field=models.ManyToManyField(null=True, related_name='assigned_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
