# Generated by Django 4.2.7 on 2023-11-30 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0013_alter_topic_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
